name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PROTECTED_BRANCH_TOKEN }}
    - name: Setup Node Version 1
      uses: actions/setup-node@v2
      with:
         node-version: ${{ secrets.NODE_VERSION }}
    - name: Build 
      run: |
        echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc
        npm install cross-env
        npm install   
        npm run production
    - name: Push to repo  
      run: |
        git add -f ./assets
        git diff --cached --name-only
        if git diff --cached --name-only ./assets | grep .; then
        git config --global user.name ${{secrets.GIT_DEVOPS_USERNAME}}
        git config --global user.email "${{secrets.GIT_DEVOPS_EMAIL}}@users.noreply.github.com"
        git commit -m "Auto build assest 😎"
        git push -f
        else
          echo "No New files gentrated for dist directory"
        fi
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Dispatch release new version
      uses: mvasigh/dispatch-action@main
      with:
        token: '${{ secrets.PACKAGES_ACCESS_TOKEN }}'
        event_type: release
    
