name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # @see https://github.com/anothrNick/github-tag-action#bumping
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: npm run production
        run: |
          node -v
          npm -v
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> ~/.npmrc
          npm install cross-env
          npm install
          npm run production
      - name: Commit Assets If Different
        run: |
          git add -f ./assets
          git diff --cached --name-only
          if git diff --cached --name-only ./assets | grep .; then
           git config --global user.name ${{secrets.GIT_DEVOPS_USERNAME}}
           git config --global user.email "${{secrets.GIT_DEVOPS_EMAIL}}@users.noreply.github.com"
           git remote set-url origin https://x-access-token:${{ secrets.PERSIONAL_TOKEN }}@github.com/$GITHUB_REPOSITORY
           git commit -m "Auto Build Assets 😎"
           git push
          else
            echo "No New files gentrated for assets directory"
          fi
      - name: Auto Tagging
        id: autotagger
        uses: anothrNick/github-tag-action@1.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: master
          DEFAULT_BUMP: patch
  
